#!/usr/bin/env sh
# Placeholder gradlew - will be generated by `gradle wrapper` in CI if missing
# For local dev: run `gradle wrapper --gradle-version 8.9` to generate real wrapper
echo "Gradle wrapper not found. Run: gradle wrapper --gradle-version 8.9"
exit 1
